#!/bin/bash

if [[ $# -eq 0 ]]
then
    (
	echo "Usage: $(basename $0) MAIN ..."
	echo " MAIN is one of send, sync, dump" # , replay, monitor"
    ) 1>&2
    exit 1
fi

CPF="fk.classpath"
if [ ! -e "$CPF" ]; then
    echo "Need to create classpath file"
    echo "Ensure maven is up to date with the latest snapshots and then run"
    echo "  mvn dependency:build-classpath -DincludeScope=runtime -Dmdep.outputFile=$CPF"
    exit 1
fi
CP="$(cat $CPF)"
CPJ="$(echo target/jena-kafka-client-*.jar)"
CP="$CPJ:$CP"

CMD=$1
shift
ARGS="$@"
K_ARGS="-s localhost:9092"
CMD_PKG=org.apache.jena.kafka.cmd

case $CMD in
    ## Send a file.
    "send")      CMD="$CMD_PKG".FK_Send ;;
    ## Dump topic
    "dump")      CMD="$CMD_PKG".FK_DumpTopic ;;
    ## Classpath
    "CP")
	echo "$CPJ"
## 	for X in $(echo $CP | tr ":" "\n")
## 	do
## 	    echo $X
## 	done
	exit
	;;
    
##     #### Experimental.
##     ## Dump topic
##     "monitor")      CMD=cmd2.FK_Monitor ;;
##     ## replay
##     "replay")      CMD=cmd2.FK_Replay ;;
    
    *)
	echo "Warning: unrecognised command" 1>&2
	exit
    ;;
esac

java $JVM_ARGS -cp "$CP" $CMD $K_ARGS $ARGS
